;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        comment-indent-new-line
        electric-graphviz-dot-semi
        electric-newline-and-maybe-indent
        forward-sexp
        howm-save-buffer
        indent-for-tab-command
        kill-region
        org-delete-char
        org-force-self-insert
        org-self-insert-command
        org-seq-end
        org-seq-home
        org-todo
        org-yank
        seq-end
        seq-home
        sp-backward-sexp
        sp-forward-sexp
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
