;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        forward-sexp
        indent-for-tab-command
        kill-region
        seq-end
        seq-home
        sp-backward-sexp
        sp-forward-sexp
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
